#!/bin/bash

# Build and show errors
error(){
    echo -e "\033[0;31m${1}\033[0m"
}

# Build and show notices
notice(){
    echo -e "\033[1;33m${1}\033[0m"
}

# Build and show successes
success(){
    echo -e "\033[1;32m${1}\033[0m"
}
