#!/bin/bash

# Suspend the current session
nap(){
    local cmd="dbus-send --system --print-reply"
    cmd="${cmd} --dest=org.freedesktop.login1"
    cmd="${cmd} /org/freedesktop/login1"
    cmd="${cmd} org.freedesktop.login1.Manager.Suspend boolean:true"
    eval "${cmd}" > /dev/null
}
