#!/bin/bash

record(){

    # Open OSB if it is not already open.
    local check=$(wmctrl -lp | grep OBS)
    if (( ${#check} < 1 ));
    then
        $(nohup obs >/dev/null 2>&1 &)
    fi

    # Get list of open windows including PID numbers.
    local windows=$(wmctrl -lp)

    # Split list of windows into an array.
    local save_ifs=$IFS
    IFS=$'\n'
    windows=($windows)
    IFS=$' '

    # Make pair arrays of the window IDs and names
    local window_ids=()
    local window_names=()

    for line in "${windows[@]}";
    do
        line=($line)
        window_ids+=( ${line[0]} )
        window_names+=($(ps -p ${line[2]} -o comm=))
    done
    IFS=$save_ifs

    # Print a table of open windows allowing the user to choose what to add to the recording area.
    for index in ${!window_names[@]};
    do
        printf '%-25s' "[${index}] ${window_names[index]}"
        if (( $(( $index + 1 )) % 4 == 0 ));
        then
            printf '\n' ''
        fi
    done
    printf '\n' ''

    # Ask the user which windows to add to the recording area.
    echo 'Enter window number(s) followed by a space that you like to add to the recording area. Yellow numbers are already selected:'

    read chosen

    # Turn user input into an array and process.
    save_ifs=$IFS
    IFS=$' '
    chosen=($chosen)

    for index in ${chosen[@]};
    do
        eval "wmctrl -ir ${window_ids[$index]} -d remove,maximized_vert,maximized_horz"
        eval "wmctrl -ir ${window_ids[$index]} -e 0,0,0,1920,1080"
    done
}

record
